version: 2

upx:
  - enabled: true
    goos: [linux, darwin]
    compress: best
    lzma: true

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags: >-
      -s -w
      -X github.com/marianozunino/goq/cmd.Version={{.Version}}
      -extldflags '-static'
    flags:
      - -trimpath

release:
  github:
    owner: marianozunino
    name: goq
  name_template: "{{.ProjectName}} v{{.Version}}"
  disable: false
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
